version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4571:4571"            # LocalStack Web UI (optional)
    environment:
      - SERVICES=lambda,sqs,apigateway,iam,cloudformation,logs
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "./lambda:/var/task"   # Mount lambda code
      - "/var/run/docker.sock:/var/run/docker.sock"
